services:
    serasa_br_ag_db_test:
        image: postgres:14.18
        container_name: serasa_br_ag_db_test
        restart: always
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_DB=br_ag_db_test
            - POSTGRES_USER=br_ag_user_test
            - POSTGRES_PASSWORD=br_ag_password_test
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
            interval: 1s
            timeout: 5s
            retries: 10
        volumes:
            - pgdatatest:/var/lib/postgresql/data
volumes:
    pgdatatest: