services:
    serasa_br_ag:
        build: .
        container_name: serasa_br_ag
        ports:
            - '3001:3000'
        environment:
            - PORT=3000
            - NODE_ENV=dev
        env_file: .env.dev
        depends_on:
            serasa_br_ag_db:
                condition: service_healthy
        volumes:
            - ./src:/usr/src/app/src
    serasa_br_ag_db:
        image: postgres:14.18
        container_name: serasa_br_ag_db
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=br_ag_db
            - POSTGRES_USER=br_ag_user
            - POSTGRES_PASSWORD=br_ag_password
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
            interval: 1s
            timeout: 5s
            retries: 10
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata: